package com.xiaopeng.xuiservice.xapp;
/* loaded from: classes5.dex */
public class Constants {
    public static final String ACTION_ACTIVITY_CHANGED = "com.xiaopeng.intent.action.ACTIVITY_CHANGED";
    public static final String ACTION_APPLET_LIST = "com.xiaopeng.intent.action.SHOW_APPLET_LIST";
    public static final String ACTION_APP_LIST = "com.xiaopeng.intent.action.SHOW_APP_LIST";
    public static final String ACTION_APP_STORE = "com.xiaopeng.intent.action.SHOW_APP_STORE";
    public static final String ACTION_APP_UPDATE_DIALOG = "com.xiaopeng.intent.action.SHOW_APP_UPDATE_DIALOG";
    public static final String ACTION_CLOSE_USER_MANUAL = "com.xiaopeng.usermanual.ACTION_CLOSE";
    public static final String ACTION_DIALOG_CHANGED = "com.xiaopeng.intent.action.XUI_DIALOG_CHANGED";
    public static final String ACTION_LAUNCH_USER_MANUAL = "com.xiaopeng.usermanual.ACTION_LAUNCH";
    public static final String ACTION_SHOW_TOAST = "com.xiaopeng.xui.intent.action.TOAST";
    public static final String ACTIVITY_MAIN_MAP = "com.xiaopeng.montecarlo.MainActivity";
    public static final int APP_STORE_ACTION_ONLY_DOWNLOAD = 2;
    public static final int APP_STORE_ACTION_ONLY_SHOW = 0;
    public static final int APP_STORE_ACTION_SHOW_DOWNLOAD = 1;
    public static final String DRIVER_SCREEN_BRIGHTNESS_MODE = "screen_brightness_mode_0";
    public static final String EXTRA_APP_STORE_PACKAGE = "com.xiaopeng.appstore.intent.extra.PACKAGE";
    public static final String EXTRA_APP_STORE_SCREEN = "com.xiaopeng.appstore.intent.extra.SCREEN";
    public static final String EXTRA_APP_STORE_STATE = "com.xiaopeng.appstore.intent.extra.STATE";
    public static final String EXTRA_COMPONENT = "android.intent.extra.COMPONENT";
    public static final String EXTRA_FLAGS = "android.intent.extra.FLAGS";
    public static final String EXTRA_MINIPROGRAM = "android.intent.extra.mini.PROGRAM";
    public static final float FADE_ALPHA = 0.5f;
    public static final int FADE_OUT_TIME = 5000;
    public static final int FLAG_ACTIVITY_LAUNCH_HOME = 536870912;
    public static final int FLAG_ACTIVITY_LAUNCH_PANEL = 256;
    public static final int FLAG_MINI_PROG = 512;
    public static final int HIDE_QSPANEL_TIME = 200;
    public static final float HIGH_ALPHA = 0.9f;
    public static final String KEY_AVAS_SPEAKER = "avas_speaker";
    public static final int MAIN_DRIVER_SOUND_LOCATION = 1;
    public static final int MAX_ACTIVITY_RECORD_NUM = 500;
    public static final int MAX_TEXT_LINE_NUM = 2;
    public static final String META_ACTIVITY_WINDOW_LEVEL = "window_level";
    public static final String PACKAGE_ALIPAY_AROME = "com.alipay.arome.app";
    public static final String PACKAGE_CAR_ACCOUNT = "com.xiaopeng.caraccount";
    public static final String PACKAGE_CHANGBA = "com.changba.sd";
    public static final String PACKAGE_NAPA = "com.xiaopeng.napa";
    public static final String PACKAGE_QIYI_IV = "com.qiyi.video.iv";
    public static final String PACKAGE_THUNDER = "com.thunder.carplay";
    public static final String PACKAGE_YOUKU_IOT = "com.youku.car";
    public static final String PASSENGER_SCREEN_BRIGHTNESS = "screen_brightness_1";
    public static final String PASSENGER_SCREEN_BRIGHTNESS_MODE = "screen_brightness_mode_1";
    public static final String PERMISSION_APP_SUPER_RUNNING = "android.permission.SUPER_APPLICATION_RUNNING";
    public static final int PERMISSION_XPILOT_DENIED = 4;
    public static final String SCREEN_BRIGHTNESS_MODE_SYNC = "screen_brightness_mode_sync";
    public static final String URI_SHOW_APP_DETAIL = "market://details?id=";
    public static final String PACKAGE_OTA = "com.xiaopeng.ota";
    public static final String PACKAGE_CAR_CONTROL = "com.xiaopeng.carcontrol";
    public static final String PACKAGE_AI_ASSISTANT = "com.xiaopeng.aiassistant";
    public static final String PACKAGE_APP_STORE = "com.xiaopeng.appstore";
    public static final String PACKAGE_USERMANUAL = "com.xiaopeng.usermanual";
    public static final String PACKAGE_MONTECARLO = "com.xiaopeng.montecarlo";
    public static final String[] PACKAGE_SYSTEM_APPS = {PACKAGE_OTA, PACKAGE_CAR_CONTROL, PACKAGE_AI_ASSISTANT, PACKAGE_APP_STORE, "com.alipay.arome.app", PACKAGE_USERMANUAL, PACKAGE_MONTECARLO};
}
